name: Build, Test & Publish to PyPI

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*' # Alternative: only build for tags.
  pull_request:

jobs:
  build:
    name: Build wheel & conda package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install UV
        uses: prefix-dev/setup-pixi@0.8
        with:
          pixi-version: 0.68.1
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Build sdist
        run: |
          uv build
          pixi build
          ls dist/
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheel
          path: dist/*.whl



  upload_pypi:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    permissions:
        # IMPORTANT: this permission is mandatory for trusted publishing
        id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1